config/routes.rb
Rails.application.routes.draw do
  

  resources :projects do 
    resources :tickets 
  end 
  

    root "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, presence: true 
  validates :title, length: {minimum: 5}
 
  has_many :tickets, dependent: :delete_all 
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  validates :title, presence: true
  validates :description, length: {minimum: 10}
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  def index
  end

  def show
   
  end
  
  def new 
    @project = Project.new 
  end 
  
  def index 
    @projects = Project.all 
  end 
  
  def create
    @project = Project.new(project_params)
    if @project.save 
      redirect_to project_path(@project)
      flash[:notice] = "Project has been created."
    else 
      render "new"
    end 
  end 
  
  def edit
    
  end 
  
  def update 
    if @project.update(project_params) 
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else 
      flash[:alert] = "Project has not been updated."
      render :edit 
    end 
  end 
  
  def destroy 
    if @project.destroy 
      flash[:notice] = "Project has been destroyed!"
      redirect_to projects_url 
    else 
      flash[:alert] = "Oops, something went wrong!"
    end
  end 
  private 
  
  def project_params
    params.require(:project).permit(:title, :description)
  end 
  
  def set_project 
    @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you're looking for could not be found."
    redirect_to projects_url 
  end 
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_project
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
   
  def new
    @ticket = @project.tickets.build 
  end
  
  def create 
    @ticket = @project.tickets.build(ticket_params)
    if @ticket.save 
      flash[:notice] = "Ticket has been created."
      redirect_to project_ticket_path(@project,@ticket)
    else
      flash[:alert] = "Ticket wasn't created!"
      render :new 
    end 
  end 
  
  def edit
  end
  
  def update 
    if  @ticket.update(ticket_params)
      flash[:notice] = "Ticket has been updated."
      redirect_to project_ticket_path(@project,@ticket)
    else 
      flash[:alert] = "Tickket has not been updated."
      render :edit 
    end 
  end 
  
  def show
    
  end
  
  
  def destroy 
    if @ticket.destroy
      flash[:notice] = "Ticket has been deleted."
      redirect_to @project 
    else
      flash[:alert]= "Ticket has not been deleted."
    end 
  end 
  
  private 
  
  def set_ticket 
    @ticket = @project.tickets.find(params[:id])
  end 
  
  def set_project 
    @project = Project.find(params[:project_id])
  end 
  def ticket_params
    params.require(:ticket).permit(:title,:description)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title) 
    default = 'Ticket Tracker'
    if title.empty?
      default
    else 
      default + " | " + title 
    end 
  end 
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title(yield :title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |f_type, f_message| %>
  <%= content_tag(:div, f_message, class: f_type) %> 
<% end %> 
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %> 
  <% if @project.errors.any? %>
    <div class="error_explanation">
      <p>You have <%= pluralize(@project.errors.count, "error")%></p>
      <ul>
        <% @project.errors.full_messages.each do |message| %> 
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
  <%= f.label :title %> 
  <%= f.text_field :title %> 

  <%= f.label :description %> 
  <%= f.text_field :description %> 

  <%= f.submit 'Create Project' %> 

<% end %>

app/views/projects/edit.html.erb
<%= form_for @project do |f| %> 
  <% if @project.errors.any? %>
    <div class="error_explanation">
      <p>You have <%= pluralize(@project.errors.count, "error")%></p>
      <ul>
        <% @project.errors.full_messages.each do |message| %> 
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
  <%= f.label :title %> 
  <%= f.text_field :title %> 

  <%= f.label :description %> 
  <%= f.text_field :description %> 

  <%= f.submit 'Edit Project' %> 

<% end %>

app/views/projects/index.html.erb
<%= content_for :title do %>
  Projects
<% end %> 

<h1 class="text-center page_title">Projects</h1>

<table class="table project_list table-bordered">
  <thead>
  </thead>
  <tbody>
    <% @projects.each do |p| %>
    <tr>
      <td class="one show"><%= link_to p.title,project_path(p) %></td>
      <td class="two edit"><%= link_to "Edit", edit_project_path(p)%></td>
      <td class="three delete"><%= link_to "Delete", project_path(p), method: :delete, data: {confirm: "Are you sure you won't to destroy project?"} %></td> 
    </tr>
    <% end %> 
  </tbody>
</table>

<%= link_to 'New Project', new_project_path %> 
 

app/views/projects/new.html.erb
<%= render 'form' %> 

app/views/projects/show.html.erb
<%= provide(:title, "Project #{@project.id}")%>
<h1>Projects#show</h1>
<ul id="tickets">
  <%= @project.tickets.each do |ticket| %> 
    <li><%= link_to ticket.title, project_ticket_path(@project,ticket) %></li>
  <% end %>  
</ul>

<%= link_to "Create Ticket", new_project_ticket_path(@project.id) %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="error_messages">
    <p>You have <%= pluralize(object.errors.count, 'error')%></p>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
 <% end %>

app/views/tickets/_form.html.erb
<%= form_for [@project,@ticket] do |f| %> 
  <%= render "shared/errors", object: f.object %>
  <%= f.label :title %>
  <%= f.text_field :title %>
 
  <%= f.label :description %>
  <%= f.text_area :description %>
 
  <%= f.submit %>
<% end %>

app/views/tickets/edit.html.erb
<%= provide(:title, "Edit Ticket") %> 
<%= render "form" %>

app/views/tickets/new.html.erb
<%= provide(:title,"Create Ticket") %>
<%= render "form" %>

app/views/tickets/show.html.erb
<%= provide(:title, " Ticket #{@ticket.id}") %>

<section class="ticket_details">
  <h2><%= @ticket.title %></h2>
  <p><%= @ticket.description %></p>  
  <%= link_to "Edit Ticket", edit_project_ticket_path(@project, @ticket) %>
  <%= link_to "Delete Ticket", project_ticket_path(@project, @ticket), method: :delete, confirm: "Are you sure you want to delete ticket" %>
</section>